### PR TITLE
[FEATURE] Default pagination configuration

### PR DESCRIPTION
**Pull request by aaronsaray**
#### Issue or feature explanation
See issue #25 

#### Proposed solution/change
I added a configuration option.  Beta users will need to update their published config.  We could also modify this to have a default config() return value, but I really didn't want to do that if at all possible (then we'd have to hard-code `100` all over still, or make a constant)

### CODE REVIEW

**Comment by QuintenJustus** [comment]
Very nice feature and implementation! Just one thing, the config key, something like `pagination` looks better and makes just as much sense. So if you could change just that it's all good! Thanks for your contribution! :+1:

**Comment by aaronsaray** [comment]
There - should be all up to date.

**Comment by QuintenJustus** [comment]
Will be merged in next release.

**Comment by QuintenJustus** [comment]
Closing now, see 47c57d8cfa355299ef22a4c80119e701ae21cf65 for commit.

**Pull request closed without merging**
