### PR TITLE
[Feature] Beta dark theme

### PR DESCRIPTION
**Pull request by James-N-M**
#### PR Naming convention
[FEATURE/FIX/REFACTOR/README] Your PR title

#### Issue or feature explanation
A short explanation as to why this is needed, or, would be a great addition to Prequel! Or a reference to an open issue.
this is a theme switcher, to switch between the default light theme and a dark theme
#### Proposed solution/change
Short explanation how this was done.
This was done by creating root css variables and dark theme css variables paired with custom tailwind classes. Calling this beta because certain things definitely need more work but I feel like its at a good place right now to let people start using it. but could use a designers take on it.

### CODE REVIEW

**Comment by cjfloss** [comment]
Just a general comment.

In newer browsers you can use the CSS Media feature "prefers-color-scheme"
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by QuintenJustus** [comment]
Got any screenshots? 😄

**Comment by James-N-M** [comment]
image
image
image

**Comment by QuintenJustus** [comment]
Not too sure about the background color, too dark, I think #5b5266  would be better. What do you think?

**Comment by James-N-M** [comment]
@QuintenJustus I am open to everything, I was really unsure what colors to pick for everything. but I only have to change the variable in one place to update it all :)

**Comment by James-N-M** [comment]
page back-ground set to #5b5266 
image

**Comment by James-N-M** [comment]
it might be a good idea to let people try it, see how they feel about what colors would look best. Then I can do another issues to update the colors :)

**Comment by James-N-M** [comment]
> Not too sure about --page-background-color: #1c1c1c, too dark, I think #5b5266 would be better. I think you should keep a safe distance above #1c1c1c, don't you think?

is what the page back ground is on laravel horizon 
https://github.com/laravel/horizon/blob/3.0/resources/sass/app-dark.scss

**Comment by QuintenJustus** [comment]
My suggestion wasn’t that good I see 😁 
Just keep Laravel Horizon’s dark mode then, and like you said let users suggest any optimisations 👌 Great work!

**Comment by QuintenJustus** [comment]
Merged!
Just a few things I noticed that could be patched
- Table nth::even and nth:uneven aren't colored differently like the normal theme
- TableStatus background is still light themed
- Horizontal scroll bar still light

Could you fix these? Also it might be good to clone Prequel's Dev branch as I've added a few UI related things.

**Comment by James-N-M** [comment]
I figured since it was a dark theme id do that on purpose to the table. I also couldnt figure out how to style the scroll bar the w3 tutorial i found wasnt doing the trick, and ill fix the table status thing :) If you could create another issue for the patches that'd be great I'm going to take a day or two off working after work :))

**Comment by QuintenJustus** [comment]
Sure thing! The even/uneven row coloring is more a UX/readability fix than it is a style fix. I'll fix the scroll bar style for you! Thanks for your contributions! Enjoy your time off :+1:

**Comment by James-N-M** [comment]
Tag me in the fixes you do so I can see how you did them :)

**Comment by QuintenJustus** [comment]
@James-N-M Fixed them, see b8256ff02bf959e55526bceb77548bbd4f2cfe6d :smile:

**Pull request merged**
